version: "3"
services: 
  mysqldb: 
    container_name: mysql
    image: mysql:latest
    volumes:
      - /home/user/Desktop/db:/var/lib/mysql
    ports: 
      - "3306:3306"
    environment:
      MYSQL_DATABASE: account_db
      MYSQL_ROOT_PASSWORD: root
        